// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANDlde71KB3yrhmSlKccrd2yXq6LHFJF4',
    appId: '1:359489771990:web:7a02f1c38187a4feec2c77',
    messagingSenderId: '359489771990',
    projectId: 'first-flutter-app-a0f58',
    authDomain: 'first-flutter-app-a0f58.firebaseapp.com',
    storageBucket: 'first-flutter-app-a0f58.appspot.com',
    measurementId: 'G-WWERPX4WK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGoc_cCnUpHF_Y7PwpYq6tN3Z1_c5dEvI',
    appId: '1:359489771990:android:fb4d69183fb9381bec2c77',
    messagingSenderId: '359489771990',
    projectId: 'first-flutter-app-a0f58',
    storageBucket: 'first-flutter-app-a0f58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMo1R4AA-vnnn4D07qpatnCPiiJpIVnkM',
    appId: '1:359489771990:ios:abaca030c188fe0aec2c77',
    messagingSenderId: '359489771990',
    projectId: 'first-flutter-app-a0f58',
    storageBucket: 'first-flutter-app-a0f58.appspot.com',
    iosClientId: '359489771990-qtve5qv7o680tu9ddqv26ov7j4rer6i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMo1R4AA-vnnn4D07qpatnCPiiJpIVnkM',
    appId: '1:359489771990:ios:abaca030c188fe0aec2c77',
    messagingSenderId: '359489771990',
    projectId: 'first-flutter-app-a0f58',
    storageBucket: 'first-flutter-app-a0f58.appspot.com',
    iosClientId: '359489771990-qtve5qv7o680tu9ddqv26ov7j4rer6i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstFlutterApp',
  );
}
